# ===============================
# OAuth - Google
# ===============================
oauth.google.client-id=${GOOGLE_CLIENT_ID}
oauth.google.client-secret=${GOOGLE_CLIENT_SECRET}
oauth.redirect-uri=https://insighton.store/oauth/callback

# ===============================
# OAuth - GitHub
# ===============================
oauth.github.client-id=${GITHUB_CLIENT_ID}
oauth.github.client-secret=${GITHUB_CLIENT_SECRET}