spring.application.name=insighton-auth

eureka.client.service-url.defaultZone=http://insighton-eureka:8761/eureka/

# redis에 refresh, access를 저장 gateway에서 access 확인, auth에서 refresh 확인
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE_1}