spring.application.name=insighton-auth

eureka.client.service-url.defaultZone=http://insighton-eureka:8761/eureka/

# redis에 refresh, access를 저장 gateway에서 access 확인, auth에서 refresh 확인

eureka.instance.instance-id=true

spring.config.import=optional:configserver:http://insighton-config:8888
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}

management.endpoints.web.exposure.include=health,prometheus,auth
management.endpoint.health.show-details: always