# dev 프로파일에서만 다른 설정. 공통 설정은 application.properties 참고.
spring.config.import=classpath:config/dev/actuator.properties, classpath:config/dev/redis.properties, classpath:config/dev/db.properties, classpath:config/dev/mail.properties
spring.jpa.show-sql=true

server.port=8000

gateway-route.auth=http://localhost:8000
gateway-route.ai=http://localhost:8100
gateway-route.rule=http://localhost:8200
gateway-route.core=http://localhost:8300