spring.application.name=insighton-auth

# ===============================
# PostgreSql
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# H2 Database
# ===============================
#spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
# H2 콘솔
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ===============================
# Redis
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}

# ===============================
# jwt token keys
# ===============================
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.key-id=monitoring-key-v1
jwt.access-token-validity=15m
jwt.refresh-token-validity=14d

eureka.client.enabled=false

# ===============================
# Brevo
# ===============================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_LOGIN}
spring.mail.password=${BREVO_SMTP_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 타임아웃
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# MailHog (테스트용)
# ===============================
#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.properties.mail.smtp.auth=false
#spring.mail.properties.mail.smtp.starttls.enable=false

# 발신 이메일 주소 (코드에서 참조용)
mail.from-address=insighton@insighton.store
mail.from-name=InsightOn

# ===============================
# OAuth
# ===============================
oauth.google.client-id=${GOOGLE_CLIENT_ID}
oauth.google.client-secret=${GOOGLE_CLIENT_SECRET}
oauth.google.redirect-uri=https://insighton.store/oauth/callback